version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production